version: 0.2

phases:
  install:
    commands:
      - echo Installing .NET Core...
      - yum install -y dotnet-sdk-6.0  # Adjust based on your .NET Core version

  pre_build:
    commands:
      - echo Restoring NuGet packages...
      - dotnet restore

  build:
    commands:
      - echo Building the .NET Core application...
      - dotnet build --configuration Release

  post_build:
    commands:
      - echo Running tests...
      - dotnet test

      # Create the deployment package (zip) for EC2
      - echo Packaging the application...
      - dotnet publish --configuration Release --output out
      - zip -r application.zip ./out/*
      
      # Assuming SSH access to EC2 for deployment
      - echo Deploying to EC2 instance...
      - scp -i /path/to/key.pem application.zip ec2-user@your-ec2-instance:/path/to/deploy

      # SSH into the EC2 instance and unzip, then restart your service
      - ssh -i /path/to/key.pem ec2-user@your-ec2-instance 'unzip /path/to/deploy/application.zip -d /var/www/app && systemctl restart your-app-service'

artifacts:
  files:
    - application.zip